name: Bug Report
description: A bug has been found
labels: ["bug"]
title: "Bug: "
body:
  - type: markdown
    attributes:
      value: "Before opening a new issue, please search existing issues:  https://github.com/primecity-roleplay/issue-tracker/issues"
  - type: dropdown
    id: assurance
    attributes:
      label: Assurance
      description: Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?
      options:
        - I have read the `README.md`
    validations:
      required: true
  - type: input
    id: reporter
    attributes:
      label: Reporter
      description: Who is reporting this? Please include discord name.
      placeholder: Newton (Newton#143)
    validations:
      required: true          
  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: Write a short summary of what you are experiencing.
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: Include what steps that are needed in order to reproduce this issue.
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What are the expected results?
    validations:
      required: true
  - type: textarea
    id: actual
    attributes:
      label: Actual Results
      description: What are the actual results?
    validations:
      required: true
  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots/Videos
      description: Provide any screenshots and/or videos demonstrating the issue being experienced.
    validations:
      required: false
  - type: textarea
    id: playerdata
    attributes:
      label: Player Data
      description: Write '/info' whilst in-game and provide a screenshot of the information you are prompted.
    validations:
      required: false         
